### ISSUE TITLE
Rhythmbox 3.2 and up breaks ArtDisplay plugin

### ISSUE THREAD

**Issue by RohanVilloth** [dmo60/ArtDisplay#2]
Art Display plugin is broken since _Rhythmbox v3.2_. Plugins list doesn't show the plugin, though an inactive album cover display square still appears on the panel. It doesn't display any cover art, but just keeps showing the _rhythmbox-missing-art_ icon.
![art display plugin broken](https://cloud.githubusercontent.com/assets/3755396/7510592/8334bbb4-f4bb-11e4-9809-c4175092bd0a.png)

**Comment by timoloewe** [comment]
Thanks, I'm aware of this issue, but I don't know when I have the time to look into it.

**Comment by RohanVilloth** [comment]
Tested **fossfreedom**'s commit and it works fine on both Rhythmbox version 3.2 and 3.0.
ArtDisplay plugin on **Rhythmbox v3.2** (with **Alternate Toolbar** plugin by **fossfreedom**):
![ArtDisplay on Rhythmbox 3.2 with Alternate Toolbar](https://cloud.githubusercontent.com/assets/3755396/7550474/ed2f4616-f681-11e4-98f8-dc09c8d93952.png)

On **Rhythmbox v3.0** ( **Ubuntu 14.04LTS**'s default player):
![ArtDisplay plugin on Ubuntu 14.04LTS vanilla Rhythmbox](https://cloud.githubusercontent.com/assets/3755396/7550485/3287cb98-f682-11e4-946e-81f3dfd3884e.png)

@dmo60 I can confirm that ArtDisplay now works on Rhythmbox 3.2 without breaking previous version 3.0. Please merge **fossfreedom**'s patch upstream.

**Comment by timoloewe** [comment]
I just merged it. Thank you both for helping me out!
